spring:
  datasource:
    url: jdbc:mysql://monorail.proxy.rlwy.net:32060/railway
    username: root
    password: gG6EaE4BbbGfG23dcF3HhDaH6EC6Ge64
  jpa:
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB

file:
  upload-dir: src/main/resources/uploads

server:
  port: 5000
